pub mod transcription;
pub mod speakers;
pub mod settings;
pub mod logs;

// Glob re-exports required: tauri::generate_handler! needs hidden __cmd__*
// symbols generated by #[tauri::command] which only propagate via `pub use *`
pub use transcription::*;
pub use speakers::*;
pub use settings::*;
pub use logs::*;
